In [22]:
#1
import numpy as np 
import csv 
file_path='D:\\17A3KHDL\\LAB2\\DATA\\diem_hoc_phan.csv'
data=[]
with open(file_path, 'r', encoding='utf-8') as f:
    reader=csv.reader(f)
    header=next(reader)
    for row in reader:
        data.append(row)
diem_sinh_vien=np.array(data)[:, 2:].astype(float)
print("Dữ liệu điểm số: ")
print(diem_sinh_vien)


Dữ liệu điểm số: 
[[3.04 3.39 6.7 ]
 [5.8  6.41 6.62]
 [2.59 3.57 9.16]
 [3.81 8.78 9.24]
 [8.91 9.64 6.39]
 [3.23 4.72 6.17]
 [2.35 3.29 6.89]
 [2.48 3.81 4.84]
 [3.23 2.61 4.52]
 [7.02 9.01 9.15]
 [2.29 4.48 5.51]
 [3.51 7.19 5.13]
 [6.74 7.78 6.19]
 [9.86 4.64 3.33]
 [8.04 5.12 4.77]
 [2.74 8.88 5.8 ]
 [3.04 6.88 3.91]
 [5.87 4.41 8.84]
 [8.46 2.63 4.91]
 [3.74 6.71 3.44]
 [5.67 8.05 6.03]
 [8.12 2.46 3.87]
 [9.4  5.31 5.13]
 [3.91 5.09 8.82]
 [4.26 5.78 8.14]
 [4.41 2.66 5.4 ]
 [3.23 8.3  8.64]
 [9.25 8.29 9.1 ]
 [6.08 2.67 6.39]
 [3.85 7.71 5.75]]


In [21]:
def quy_doi_diem(diem):
    if 8.5<=diem<=10:
        return 'A' 
    elif 8.0<=diem<=8.4:
        return'B+' 
    elif 7.0<=diem<8:
        return'B' 
    elif 6.5<=diem<7:
        return'C+' 
    elif 5.5<=diem<6:
        return'C' 
    elif 5.0<=diem<5.5:
        return'D+' 
    elif 4.0<=diem<5:
        return'D'
    else:
        return'F' 
diem_chu=np.vectorize(quy_doi_diem)(diem_sinh_vien)
print("Điểm chữ của sinh viên: ")
print(diem_chu)

Điểm chữ của sinh viên: 
[['F' 'F' 'C+']
 ['C' 'F' 'C+']
 ['F' 'F' 'A']
 ['F' 'A' 'A']
 ['A' 'A' 'F']
 ['F' 'D' 'F']
 ['F' 'F' 'C+']
 ['F' 'F' 'D']
 ['F' 'F' 'D']
 ['B' 'A' 'A']
 ['F' 'D' 'C']
 ['F' 'B' 'D+']
 ['C+' 'B' 'F']
 ['A' 'D' 'F']
 ['B+' 'D+' 'D']
 ['F' 'A' 'C']
 ['F' 'C+' 'F']
 ['C' 'D' 'A']
 ['F' 'F' 'D']
 ['F' 'C+' 'F']
 ['C' 'B+' 'F']
 ['B+' 'F' 'F']
 ['A' 'D+' 'D+']
 ['F' 'D+' 'A']
 ['D' 'C' 'B+']
 ['D' 'F' 'D+']
 ['F' 'B+' 'A']
 ['A' 'B+' 'A']
 ['F' 'F' 'F']
 ['F' 'B' 'C']]


In [15]:
#3
diem_hp1=diem_sinh_vien[:, 0]
diem_hp2=diem_sinh_vien[:, 1]
diem_hp3=diem_sinh_vien[:, 2]
print("Điểm học phần 1: ")
print(diem_hp1)
print("Điểm học phần 2: ")
print(diem_hp2)
print("Điểm học phần 3: ")
print(diem_hp3)


Điểm học phần 1: 
[3.04 5.8  2.59 3.81 8.91 3.23 2.35 2.48 3.23 7.02 2.29 3.51 6.74 9.86
 8.04 2.74 3.04 5.87 8.46 3.74 5.67 8.12 9.4  3.91 4.26 4.41 3.23 9.25
 6.08 3.85]
Điểm học phần 2: 
[3.39 6.41 3.57 8.78 9.64 4.72 3.29 3.81 2.61 9.01 4.48 7.19 7.78 4.64
 5.12 8.88 6.88 4.41 2.63 6.71 8.05 2.46 5.31 5.09 5.78 2.66 8.3  8.29
 2.67 7.71]
Điểm học phần 3: 
[6.7  6.62 9.16 9.24 6.39 6.17 6.89 4.84 4.52 9.15 5.51 5.13 6.19 3.33
 4.77 5.8  3.91 8.84 4.91 3.44 6.03 3.87 5.13 8.82 8.14 5.4  8.64 9.1
 6.39 5.75]


In [17]:
#4
def phan_tich_diem(diem, ten_hoc_phan):
    tong_diem=np.sum(diem)
    diem_trung_binh=np.mean(diem)
    do_lech_chuan=np.std(diem)
    print(f"Phân tích: {ten_hoc_phan}")
    print(f"Tổng điểm: {tong_diem:.2f}")
    print(f"Điểm trung bình: {diem_trung_binh:.2f}")
    print(f"Độ lệch chuẩn: {do_lech_chuan:.2f}")
phan_tich_diem(diem_hp1, "Học phần 1")
phan_tich_diem(diem_hp2, "Học phần 2")
phan_tich_diem(diem_hp3, "Học phần 3")

Phân tích: Học phần 1
Tổng điểm: 154.93
Điểm trung bình: 5.16
Độ lệch chuẩn: 2.41
Phân tích: Học phần 2
Tổng điểm: 170.27
Điểm trung bình: 5.68
Độ lệch chuẩn: 2.25
Phân tích: Học phần 3
Tổng điểm: 188.78
Điểm trung bình: 6.29
Độ lệch chuẩn: 1.81


In [24]:
#5
diem_chu_tong_hop=diem_chu.flatten()
unique, counts=np.unique(diem_chu_tong_hop, return_counts=True)
tong_ket_diem=dict(zip(unique, counts))
print("Phân tích điểm tổng hợp: ")
for diem, so_luong in tong_ket_diem.items():
    print(f"Số lượng sinh viên đạt điểm{diem}: {so_luong}")

Phân tích điểm tổng hợp: 
Số lượng sinh viên đạt điểmA: 15
Số lượng sinh viên đạt điểmB: 4
Số lượng sinh viên đạt điểmB+: 6
Số lượng sinh viên đạt điểmC: 7
Số lượng sinh viên đạt điểmC+: 6
Số lượng sinh viên đạt điểmD: 10
Số lượng sinh viên đạt điểmD+: 6
Số lượng sinh viên đạt điểmF: 36
